server:
  port: 8080

spring:
  application:
    name: RentABook
  datasource:
    url: jdbc:postgresql://localhost:5432/rentabook
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

springdoc:
  api-docs:
    path: /api-docs
    pathsToMatch: /api/**
    swagger-ui:
      use-root-path: true

